### ISSUE TITLE
[Feature request] Closing sidebar when clicking outside.

### ISSUE THREAD

**Issue by threeid** [tranbathanhtung/re-jok#1]
Component: Sidebar
Link: https://re-jok.herokuapp.com/components/sidebar

Step to reproduce
1. Open sidebar in any direction.
2. Click outside, sidebar isn't close.

Expected:

2. Click outside, sidebar should close.

Possible solutions:
https://stackoverflow.com/questions/32553158/detect-click-outside-react-component

**Comment by tranbathanhtung** [comment]
Thanks for feedback but It's like https://v0.material-ui.com/#/components/drawer... It's has opacity property .. if it's true, you can click outside to close sidebar... you can see more on API 👍
