### ISSUE TITLE
Module can't resolve Styled-components in /core/Alert/style.js

### ISSUE THREAD

**Issue by ekimkael** [tranbathanhtung/re-jok#2]
Hi,
When trying to start my react app when i'd installed re-jok, i faced this error.
Really want to try the package can someone helps me?

**Comment by tranbathanhtung** [comment]
Hi @iamKael , Sorry for my mistake ... because re-jok built with styled-components, so you must install both styled-components and re-jok ... run npm install --save styled-components@3.4.0 or yarn add styled-component@3.4.0 to fix this

**Comment by ekimkael** [comment]
Okay thanks
